[project]
name = "exercise-1"
version = "0.1.0"
description = "Solves a maze with RL techniques."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
]
